mod api_versions;
#[doc(hidden)]
pub mod capabilities;
pub mod codec;
pub mod connection;
mod create_topics;
mod describe_cluster;
mod describe_configs;
mod describe_groups;
mod describe_topic_partitions;
mod discovery;
pub mod dispatcher;
#[allow(dead_code)] // ERROR_RESPONSE_API_KEYS is a test-enforced coverage declaration.
mod error_response;
mod fetch;
mod find_coordinator;
pub mod frame;
mod group_error;
mod heartbeat;
mod init_producer_id;
mod join_group;
mod leave_group;
mod list_groups;
mod list_offsets;
mod metadata;
mod offset_commit;
mod offset_fetch;
mod produce;
mod request_router;
mod sync_group;
